services:
  - type: web
    name: community-support-system
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/supportsystem-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: PROD_DB_URL
        value: jdbc:postgresql://ep-sparkling-sky-a44gtbjp-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: PROD_DB_USERNAME
        value: neondb_owner
      - key: PROD_DB_PASSWORD
        value: npg_0hEk5QoiUsKO
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://community-support-frontend.vercel.app,http://localhost:3000
      - key: LOGGING_LEVEL_ROOT
        value: INFO
      - key: LOGGING_LEVEL_APP
        value: INFO